### ISSUE TITLE
Error- at least 1 trait in prediction table was entirely missing values

### ISSUE THREAD

**Issue by anisha0826** [picrust/q2-picrust2#13]
Hi! I'm using the script hsp.py to output the nearest-sequenced taxon index (NSTI) values for each ASV, to correspond to the nearest 16S sequence and I am running into this error:
Error running this command:
Rscript /home/nish89/miniconda3/envs/MoMent/lib/python3.6/site-packages/picrust2/Rscripts/castor_hsp.R out.tre /tmp/tmpqhzcmb7m/subset_tab_0 mp 0.5 FALSE FALSE /tmp/tmpk9tvxgsd/predicted_counts.txt /tmp/tmpk9tvxgsd/predicted_ci.txt 100

Standard error of the above failed command:
Error: 
Error - at least one trait in the prediction table was entirely missing values.
Execution halted

I am new to metagenome inference and have been closely following the PICRUSt2 Tutorial. I am confused as to why there are missing values from out.tre, my output from placing my study ASVs into a reference tree. 

Any help is greatly appreciated!

**Comment by gavinmdouglas** [comment]
Hi @anisha0826,

Did you happen to use SEPP for the placement approach?

One thing you can try to address this error is to set `-e 0`, which I think will likely fix it.


Cheers,

Gavin

**Comment by anisha0826** [comment]
Thanks so much! That worked! Yes, I did use SEPP for the placement method because I don't think I have enough ram for EPA-NG. I will try and use a computer at my institution and try EPA-NG. What exactly does `-e 0` do?

**Comment by gavinmdouglas** [comment]
Hi there,

That setting is this:

```Setting for maximum parisomony hidden-state prediction. Specifies weighting transition costs by the inverse length of edge lengths. If 0, then edge lengths do not influence predictions. Must be a non-negative real-valued number (default: 0.5).```

I've found that sometimes for some reason that setting this parameter with SEPP-placed data that this error occurs, but I'm not sure why. The predictions are still highly correlated either way, so I don't think it's a big concern.

**Comment by anisha0826** [comment]
Hi! Thanks again! Last thing: when using the metagenome_pipeline.py with my lab data, the only outputs I am getting are `seqtab_norm.tsv.gz` and `weighted_nsti.tsv.gz`.  I am not getting `pred_metagenome_unstrat.tsv.gz `or `pred_metagenome_contrib.tsv.gz`. Is this somehow an artifact of using SEPP earlier in the picrust2 pipeline? 

`metagenome_pipeline.py -i ../run1.biom -m marker_predicted_and_nsti.tsv.gz -f EC_predicted.tsv.gz \-o EC_metagenome_out --strat_out` After running this script this is the output:
`11 of 6811 ASVs were above the max NSTI cut-off of 2.0 and were removed from the downstream analyses.
Killed`
Does 'Killed' mean that there was not enough ram to run the script and therefore pred_metagenome_unstrat.tsv.gz ` and `pred_metagenome_contrib.tsv.gz` are not produced?
Thanks so much!

**Comment by gavinmdouglas** [comment]
Hi there,

Yes unfortunately that indicates that it was killed, likely due to insufficient RAM.
