### ISSUE TITLE
Directory not empty

### ISSUE THREAD

**Issue by MalbertRogers** [picrust/q2-picrust2#15]
I've seen some closed issue on ths topic, but is the only solution to actually go into some code and adapt it myself? Isn't there a real/permanent fix for this yet? I wouldn't mind fixing it through adaptation of the code, but it will make it a bit more difficult for me when multiple users on our system eventually install and try out this plugin out, since I would have to first adapt it for every user, which is obviously not ideal. 

So, any other ideas or fixes would be welcome! Thanks!

I'm on CentOS7 and trying to run this command: 

```qiime picrust2 full-pipeline --i-table 02-output-dada2-pe-unfiltered/00-table-repseqs/table.qza --i-seq 02-output-dada2-pe-unfiltered/00-table-repseqs/repseqs.qza --output-dir q2-picrust2_output --p-placement-tool sepp --p-threads 4 --p-hsp-method mp --p-max-nsti 2 --verbose```

Thanks for developing this, by the way! I would much prefer this plugin over the stand-alone version (if it ends up working fine).

**Comment by gavinmdouglas** [comment]
Thanks for reporting this again! I wasn't able to reproduce the problem so I was hoping it was a one-off problem back then, but I see it maybe could be a CentOS related problem? Anyway, I'll be sure to fix this soon when I get a chance.


Cheers,

Gavin
