### ISSUE TITLE
q2-picrust2 for q2-2022.8

### ISSUE THREAD

**Issue by ARW-UBT** [picrust/q2-picrust2#16]
Hi, 
I have tried to install q2-picrust2 in the most recent q2-2022.8 environment, but the install command (conda install q2-picrust2=2021.11 -c conda-forge -c bioconda -c gavinmdouglas) did not complete. 

You placed on the q2 Library site the following note: "Note that the plugin version for qiime2-2021.11 is specified."
Will the q2-picrust2=2021.11 work together with the latest q2 release?

Thanks

**Comment by gavinmdouglas** [comment]
Hi there,

Sorry that I missed this - the issue was that the 2021.11 q2-picrust2 was incompatible with QIIME 2 2022.8. I just released a new version of q2-picrust2 for QIIME 2 2023.2, which you should be able to use with the latest version.


Cheers,

Gavin
