### ISSUE TITLE
Recommandations

### ISSUE THREAD

**Issue by nolarifi** [picrust/q2-picrust2#18]
I recently came across this publication at github https://github.com/gavinmdouglas/q2-picrust2/issues/9  and it resonated with some queries I've had in mind. 
I'd truly appreciate it if you could spare some time to address a few questions related to the topic. I believe your perspective and knowledge could greatly benefit my understanding.

For thr prediction of functional analysis on ITS. As far as I understood we can use picrust2. In the github repo you gave the demonstration/explanation for 16s rRNA what I should change in the command lines in order to make it applicable on ITS. 
thank you  in advance

**Comment by gavinmdouglas** [comment]
Hi there,

Sorry for missing this. Likely no longer relevant to you, but you can see this response on our FAQ regarding your query: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-can-i-run-a-custom-or-non-default-database-such-as-the-fungi-18s-and-its-databases
