### ISSUE TITLE
q2-picrust2 plugin part of official qiime2?

### ISSUE THREAD

**Issue by danicic7** [picrust/q2-picrust2#2]
Hi,
Is there any information on when will q2-picrust2 plugin be officially part of QIIME2? I mean be part of qiime2 docker image?

Thank you!

Alex

**Comment by gavinmdouglas** [comment]
This should be straight-forward once q2-picrust2 can be installed with conda, but it isn't currently. I don't have timeline for this right now unfortunately though!
