### ISSUE TITLE
hsp.py error for QIIME2 Plugin

### ISSUE THREAD

**Issue by kris-budd** [picrust/q2-picrust2#3]
Running with the following error 
qiime picrust2 custom-tree-pipeline --i-table /home/qiime2/picrust2-2.0.3-b/mine/table.qza \
>                                     --i-tree /home/qiime2/picrust2-2.0.3-b/mine/picrust_setup/tree.qza \
>                                     --output-dir /home/qiime2/picrust2-2.0.3-b/mine/output
Error running this command:
hsp.py -i KO -t /tmp/tmp6khk89rc/placed_seqs.tre -p 1 -o /tmp/tmp6khk89rc/picrust2_out/KO_predicted -m mp
(qiime2-2018.11)

Any thoughts on how to fix this issue?

**Comment by gavinmdouglas** [comment]
Would you mind sending me the two input files table.qza and tree.qza to gavin.douglasXY.Z

X=@
Y=dal
z=ca

**Comment by kris-budd** [comment]
Sent files to your email address. Please let me know if you are having any issues with them or any potential solutions to the error

**Comment by gavinmdouglas** [comment]
I ran ```hsp.py -t tree.nwk -o tmp_out -i KO``` (where tree.nwk is the exported version of tree.qza) and the job finished in 36.5 minutes and took 3.7 GB of RAM. Are you running the command on a computer with really limited RAM?

Alternatively if you export the treefile and run the same command I did you will likely get an error that would be more informative.

**Comment by kris-budd** [comment]
Hi Gavin 

Sorry, I got excited that it was working and completely dropped off. I increased memory to 5 GB and worked like a charm. Thank you so much for you help!

**Comment by gavinmdouglas** [comment]
Good to hear!
