### ISSUE TITLE
q2 picrust2 KO-output by sample instead of aggregated?

### ISSUE THREAD

**Issue by mpb02** [picrust/q2-picrust2#4]
I followed the q2-picrust2 tutorial with both the tutorial files and my own. I believe my execution was successful – resulted in all four output files which matched the data shown in the tutorial (no errors). The predicted functions currently seem to be aggregated for all samples by function, specifically looking at the KEGG Orthlog output file. Is there a way to split that so it displays predicted functions for each respective sample? 

Thanks.

**Comment by gavinmdouglas** [comment]
Hi @mpb02, just to clarify you're looking for a table with the predicted functions per sequence?

If so these files are referred to as "stratified" in PICRUSt2 and are available in the stand-alone version. I haven't implemented stratified output in the QIIME2 version yet.

**Comment by mpb02** [comment]
Hey @gavinmdouglas, I'm not necessarily looking for the predicted functions per sequence.  I'm more interested in comparing predicted functions across samples, e.g. freq=500 of K01111 in sample 1 vs freq=10000 in sample 2.  I don't believe this is "stratified," although my language may be incorrect.

I attached a truncated screenshot of the feature table from the ko-metagenome.qza output.  This data is from the [tutorial](https://github.com/picrust/picrust2/wiki/q2-picrust2-Tutorial).  The feature table only shows the total frequency (middle column) and total number of samples (far right column) per KO as opposed to the frequency of that respective KO per sample like the tutorial states should be displayed.

> "ko_metagenome.qza - KO metagenome predictions (rows are KOs and columns are samples)"

For instance, K16331 is predicted for which 6 samples out of the 11 total?  And what is the frequency for each of those 6 samples?  Am I doing something incorrectly that is causing my ko-metagenome feature table to not display correctly?

Thanks.

<img width="1037" alt="screen shot 2019-02-03 at 3 04 36 pm" src="https://user-images.githubusercontent.com/47288217/52182016-abbfea80-27c6-11e9-8441-b2ff91d3069f.png">

**Comment by gavinmdouglas** [comment]
What commands are you using to create or view that table?

What is output if you run:

```
qiime tools export --input-path ko_metagenome.qza --output-path tab_exported
biom convert -i tab_exported/feature-table.biom -o tab_exported/feature-table.biom.tsv --to-tsv
head tab_exported/feature-table.biom.tsv
```

**Comment by mpb02** [comment]
That looks much better - thanks!

I was summarizing and visualizing as a .qzv which is what I'm used to doing with the majority of our pipeline output files.  

> qiime feature-table summarize --i-table q2-picrust2_output/ko_metagenome.qza --o-visualization q2-picrust2_output/ko_metagenome.qzv"

New output is below.  Thanks for your help.

<img width="1306" alt="screen shot 2019-02-03 at 5 43 34 pm" src="https://user-images.githubusercontent.com/47288217/52183967-5e9a4380-27db-11e9-9ab8-e4214d8ffe10.png">
